spring:
  datasource:
    url: ${QA_SERVICE_DB_URL}
    username: ${QA_SERVICE_DB_USER}
    password: ${QA_SERVICE_DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${QA_SERVICE_REDIS_HOST}
      port: ${QA_SERVICE_REDIS_PORT}

  kafka:
    bootstrap-servers: ${QA_SERVICE_KAFKA_BOOTSTRAP_SERVERS}

server:
  port: ${QA_SERVICE_SERVER_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${QA_SERVICE_EUREKA_URL}

logging:
  level:
    root: INFO
    br.com.leilao: INFO
