spring:
  application:
    name: QA-SERVICE

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: qa-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cloud:
    openfeign:
      client:
        config:
          auctionService:
            connectTimeout: 2000
            readTimeout: 2000
            loggerLevel: BASIC
          user-service:
            connectTimeout: 2000
            readTimeout: 2000
            loggerLevel: BASIC
      circuitbreaker:
        enabled: true

  cache:
    type: redis

app:
  kafka:
    topics:
      qa-review-created-pending: "qa.review.created-pending"
      qa-review-approved: "reviews.qa.approved"
      qa-review-rejected: "reviews.qa.rejected"
      notify-question-approved: "qa.question.approved"
      notify-answer-approved: "qa.answer.approved"
      notify-question-rejected: "qa.question.rejected"
      notify-answer-rejected: "qa.answer.rejected"
    redis:
      time-to-live: 60m
  rate-limit:
    actions:
      create-question:
        limit: 10
        window-seconds: 60
      create-answer:
        limit: 10
        window-seconds: 60

server:
  port: ${QA_SERVICE_PORT}

eureka:
  client:
    enabled: true
  instance:
    preferIpAddress: true

#Actuator e Resilience4j
management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers, prometheus
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      auctionService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      user-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      auctionService:
        maxAttempts: 3
        waitDuration: 2s
      user-service:
        maxAttempts: 3
        waitDuration: 2s