spring:
  datasource:
    url: jdbc:postgresql://postgres-qa:5432/qa_service_db
    username: ${QA_SERVICE_DB_USER}
    password: ${QA_SERVICE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${QA_SERVICE_REDIS_HOST}
      port: ${QA_SERVICE_REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

logging:
  level:
    root: INFO
    br.com.leilao: INFO
