spring:
  config:
    activate:
      on-profile: local
  cloud:
    openfeign:
      client:
        config:
          auctionService:
            url: http://localhost:8066
          user-service:
            url: http://localhost:8080
eureka:
  client:
    enabled: false
